[default]
duration = "1h"
sorting = "random"
mode = "center"
transition-time = "0ms"
initial-transition = "False"

[any]
path = "/home/nick/Pictures/black.png"

[DP-1]
path = "/home/nick/Pictures/wpaperd-achtergronden"
duration = "30s"

[HDMI-A-1]
path = "/home/nick/Pictures/wpaperd-achtergronden"
duration = "15m"
