[default]
duration = "1h"
sorting = "random"
mode = "center"
transition-time = 0
initial-transition = false

[any]
path = "/home/nick/Pictures/black.png"

[eDP-1]
path = "/home/nick/Pictures/achtergronden"
